return {
  {
    "mason-org/mason.nvim",
    opts = {
      ensure_installed = {
        "codelldb",
        "css-lsp",
        "debugpy",
        "django-template-lsp",
        "docker-compose-language-service",
        "dockerfile-language-server",
        "eslint-lsp",
        "gitui",
        "hadolint",
        "html-lsp",
        "json-lsp",
        "lemminx",
        "lua-language-server",
        "markdown-toc",
        "markdownlint-cli2",
        "marksman",
        "prettier",
        "pyright",
        "ruff",
        "shfmt",
        "stylelint",
        "stylua",
        "tailwindcss-language-server",
        "taplo",
        "uv",
        "vtsls",
        "yaml-language-server",
      },
    },
  },
}
